export const CARD_ACTIONS = {
  ADD: 'ADD_CARD',
  EDIT: 'EDIT_CARD',
  DELETE: 'DELETE_CARD',
};

export const LIST_ACTIONS = {
  ADD: 'ADD_LIST',
  EDIT_TITLE: 'EDIT_LIST_TITLE',
  DELETE: 'DELETE_LIST',

  DRAG: 'DRAG_CARD',
};
